### ISSUE TITLE
Add small note on usage

### ISSUE THREAD

**Issue by agrrh** [PLAYG0N/mkdocs-panzoom#9]
Hey there!

Thanks for plugin!

Some users found UX not quite intuitive
May be a good idea to add some info label "Press Alt / Option key to Pan & Zoom" under the chart block

**Comment by adaxi** [comment]
I also had some trouble with the UX. I was expecting to be able to pan by pressing the scroll wheel, and zooming by Ctrl+Scroll.

A bit like they do it for Google Maps: https://developers.google.com/maps/documentation/embed/embedding-map#place_mode

**Comment by PLAYG0N** [comment]
Thx for the feedback!

@agrrh Is [this](https://playg0n.github.io/mkdocs-panzoom/Mermaid/bigmermaid/) what you imagined?
Note: The styling is not finished yet

@adaxi for now I've enabled the scroll wheel to pan without pressing alt. This behavior will be configurable when I implement #8.

**Comment by agrrh** [comment]
I thought about some kind of small permanent label below the visualization, e.g.:

![Screenshot from 2024-09-04 21-34-10](https://github.com/user-attachments/assets/13bff098-37df-4e2b-8e2b-51d2fd3d65e6)
![Screenshot from 2024-09-04 21-35-22](https://github.com/user-attachments/assets/3c4fed27-fc7e-47ee-a2ef-5443c846d3a7)

Togglable label may be not quite suitable for user, who is in a rush. Today, on first sight, I've totally missed paragraph from your Demo, where "PRESS ALT" text was quite obvious.

So I think permanent label is a good option.

**Comment by adaxi** [comment]
> for now I've enabled the scroll wheel to pan without pressing alt

Great improvement!

**Comment by malanvaneck** [comment]
Thanks for the great work @PLAYG0N

**Comment by PLAYG0N** [comment]
@agrrh I added an option to always show this hint. [How to enable this](https://playg0n.github.io/mkdocs-panzoom/#always-show-hint).

**Comment by agrrh** [comment]
Thank you, this is resolved now :pray:
